name: luckypo_project
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.8
  #  fluttertoast: ^8.0.8
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  provider: ^5.0.0
  image_picker: ^0.8.4+4
  camera: any
  path_provider: ^2.0.6
  path: ^1.8.0
  flutter_svg: ^0.23.0+1
  flutter_datetime_picker: ^1.5.1
  

  #flutter_sticky_header: ^0.4.0

  flutter_staggered_grid_view: ^0.3.0

  intl: ^0.17.0 #lib format date
  hexcolor: ^2.0.5

  #custom_pop_up_menu: ^1.2.2 #https://pub.dev/packages/custom_pop_up_menu

  ink_widget: ^2.0.1 #lib click view

  modal_progress_hud_nsn: ^0.1.0-nullsafety-0 #lib custom loading api

  dio: ^4.0.3 #lib http request

  #syncfusion_flutter_signaturepad: ^19.4.56 #lib ky ten

  #percent_indicator: ^4.0.0 #https://pub.dev/packages/percent_indicator

#  internet_connection_checker: ^0.0.1+3 #lib check internet connection
  connectivity_plus: ^2.3.6

  animated_text_kit: ^4.2.1 #lib run animate text notify

  #lib open app (zalo, momo)
  device_apps: any
  android_intent_plus: ^3.1.1
  url_launcher: ^6.1.2
  package_info_plus: ^1.0.6

  webview_flutter: ^3.0.2
  socket_io_client: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  #flutter_fortune_wheel: ^1.2.0
  flutter_hooks: ^0.18.1

  pinput: ^2.2.11 #https://pub.dev/packages/pinput
  firebase_messaging: ^11.2.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1

  bs_flutter_buttons: any
  flutter_countdown_timer: ^4.1.0 #https://pub.dev/packages/flutter_countdown_timer/install
  qr_flutter: ^4.0.0
  #percent_indicator: ^2.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.0 #flutter pub run flutter_app_name
  flutter_launcher_icons: ^0.9.2 #flutter pub run flutter_launcher_icons:main
  change_app_package_name: ^0.1.3 #flutter pub run change_app_package_name:main new.package.name

  flutter_lints: ^1.0.0


flutter_app_name:
  name: "LK8386"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app_lk.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons2.ttf
